SOURCES := main.cpp
LIBRARIES := SPI Mirf SoftwareSerial CheeseSock Commons Wire Adafruit_ADXL345-master Adafruit_Sensor-master
BOARD := pro_5V
CPPFLAGS += -DNETMOD_PRINTPKT -DNETMOD_DEBUG -DACCEL -DDEMO #-DPRINT_ACCEL
include ../../../arduino.mk